module.exports = {
  extends: ['stylelint-config-standard-scss', 'stylelint-config-prettier'],

  plugins: [],
  overrides: [{ files: ['**/*.scss'], customSyntax: 'postcss-scss' }],

  rules: {
    'unit-no-unknown': true,
    'string-no-newline': true,
    'max-nesting-depth': null,
    'number-max-precision': 5,
    'time-min-milliseconds': 10,
    'length-zero-no-unit': true,
    'value-no-vendor-prefix': null,
    'property-no-vendor-prefix': null,
    'keyframe-declaration-no-important': true,
    'shorthand-property-no-redundant-values': true,
    'block-no-empty': [true, { severity: 'warning' }],
    'property-no-unknown': [true, { checkPrefixed: true }],
    'rule-empty-line-before': ['always-multi-line', { except: ['first-nested'], ignore: ['after-comment'] }],

    'at-rule-disallowed-list': ['extend'],
    'at-rule-name-newline-after': null,
    'at-rule-no-unknown': null,
    'at-rule-no-vendor-prefix': true,

    'no-descending-specificity': null,
    'no-duplicate-selectors': true,
    'no-invalid-double-slash-comments': true,
    'no-missing-end-of-source-newline': null,
    'no-unknown-animations': true,
    'no-empty-source': [true, { severity: 'warning' }],

    'color-hex-length': 'short',
    'color-named': 'never',
    'color-no-hex': null,
    'color-no-invalid-hex': true,
    'alpha-value-notation': null,

    'comment-no-empty': true,
    'comment-whitespace-inside': 'always',
    'comment-empty-line-before': [
      'always',
      { except: ['first-nested'], ignore: ['after-comment', 'stylelint-commands'] },
    ],

    'custom-media-pattern': null,
    'custom-property-pattern': null,
    'custom-property-empty-line-before': [
      'always',
      { except: ['after-custom-property', 'first-nested'], ignore: ['after-comment', 'inside-single-line-block'] },
    ],

    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': [true, { ignoreShorthands: ['/grid-template/'] }],
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-single-line-max-declarations': 0,
    'declaration-empty-line-before': [
      'always',
      { except: ['after-declaration', 'first-nested'], ignore: ['after-comment', 'inside-single-line-block'] },
    ],
    'declaration-no-important': [true, { severity: 'warning' }],

    'font-family-name-quotes': 'always-unless-keyword',
    'font-family-no-duplicate-names': true,
    'font-weight-notation': 'numeric',

    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-name-case': 'lower',
    'function-url-no-scheme-relative': true,
    'function-url-quotes': 'always',
    'function-whitespace-after': 'always',
    'function-no-unknown': [
      true,
      { ignoreFunctions: ['/^(map|math|list|string|meta)./i', '/^(fade-out|color.adjust|v-bind)/i'] },
    ],

    'media-feature-name-no-unknown': true,
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',

    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'selector-max-attribute': null,
    'selector-max-class': null,
    'selector-max-combinators': null,
    'selector-max-compound-selectors': null,
    'selector-max-id': 1,
    'selector-max-specificity': null,
    'selector-max-type': null,
    'selector-max-universal': null,
    'selector-nested-pattern': null,
    'selector-no-qualifying-type': null,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['deep'] }],
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-no-unknown': [true, { ignorePseudoElements: ['input-placeholder'] }],
    'selector-type-case': 'lower',
    'selector-type-no-unknown': true,

    'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
    'scss/at-else-closing-brace-space-after': 'always-intermediate',
    'scss/at-else-empty-line-before': 'never',
    'scss/at-else-if-parentheses-space-before': 'always',
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-function-parentheses-space-before': 'never',
    'scss/at-function-pattern': null,
    'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
    'scss/at-if-closing-brace-space-after': 'always-intermediate',
    'scss/at-import-no-partial-leading-underscore': true,
    'scss/at-mixin-argumentless-call-parentheses': 'never',
    'scss/at-mixin-parentheses-space-before': 'never',
    'scss/at-mixin-pattern': null,
    'scss/at-rule-no-unknown': true,
    'scss/declaration-nested-properties': 'never',
    'scss/declaration-nested-properties-no-divided-groups': null,
    'scss/dollar-variable-colon-space-after': 'always-single-line',
    'scss/dollar-variable-colon-space-before': 'never',
    'scss/dollar-variable-empty-line-before': null,
    'scss/dollar-variable-no-missing-interpolation': null,
    'scss/dollar-variable-pattern': null,
    'scss/double-slash-comment-empty-line-before': [
      'always',
      { except: ['first-nested'], ignore: ['between-comments', 'stylelint-commands'] },
    ],
    'scss/double-slash-comment-inline': null,
    'scss/double-slash-comment-whitespace-inside': null,
    'scss/media-feature-value-dollar-variable': null,
    'scss/operator-no-newline-after': null,
    'scss/operator-no-newline-before': null,
    'scss/operator-no-unspaced': true,
    'scss/partial-no-import': null,
    'scss/percent-placeholder-pattern': null,
    'scss/selector-no-redundant-nesting-selector': true,
  },
}
